### PR TITLE
Bot replies

### LINKED ISSUE #3: Greetings
Listen to messages (morning, night, etc.) when tagged in a message. Tag same user in same channel with random greeting.

greetings

### PR DESCRIPTION
**Pull request by log-ical**
Has the emoji replies along with the good morning, good night, etc. greetings.

Going to need to add all the greeting messages once Tony provides them. Just added one of each for testing at the moment.

I have everything except the replies themselves in the `index.js` file currently; would we want to move all of this into a separate file in the future?

### CODE REVIEW

**Comment by log-ical** [comment]
Just added all of the replies Tony provided

**Comment by ecsr** [comment]
Looks good!

> I have everything except the replies themselves in the index.js file currently; would we want to move all of this into a separate file in the future?

Yes moving all the event code in to separate files similar to how commands are implemented is probably something we want to do. [discord.js event handling example](https://discordjs.guide/creating-your-bot/event-handling.html) if you're interested in changing it otherwise I will go ahead and merge this.

**Comment by log-ical** [comment]
Moved everything over to a new file. Also, because I forgot 🙂, I added the cooldown between messages. If you don't see anything wrong we should be all good.

**Review by ecsr — APPROVED** [review]
Good job, thanks!

**Pull request merged**
